# Generated by Django 3.1.6 on 2021-09-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('styleCode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('mainImage', models.ImageField(upload_to='', verbose_name='MainImage')),
                ('subImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage')),
                ('subImage2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('subImage3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('subImage4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.maincategory')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.subcategory')),
            ],
        ),
    ]
