# Generated by Django 3.1 on 2020-08-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('style_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=30, unique=True)),
                ('product_price', models.CharField(max_length=30)),
                ('product_detail', models.TextField()),
                ('product_created', models.DateField(auto_now_add=True)),
                ('product_mainImage', models.ImageField(upload_to='', verbose_name='MainImage')),
                ('product_subImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage')),
                ('product_subImage2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.maincategory')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.subcategory')),
            ],
        ),
    ]
