# Generated by Django 3.1.6 on 2021-09-11 10:17

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=products.models.genKey, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('styleCode', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('mainImage', models.ImageField(upload_to='', verbose_name='MainImage')),
                ('subImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage')),
                ('subImage2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('subImage3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('subImage4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.maincategory')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='category.subcategory')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
