# Generated by Django 3.2.7 on 2021-09-03 02:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(auto_created=True, default=products.models.genKey, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
