# Generated by Django 3.2.7 on 2021-09-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderproduct'),
        ('products', '0004_product_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='orderProduct',
            field=models.ManyToManyField(null=True, related_name='Product', to='order.OrderProduct'),
        ),
    ]
