# Generated by Django 3.2.7 on 2021-09-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210903_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderProduct',
        ),
    ]
