# Generated by Django 3.2.7 on 2021-09-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderproduct_order'),
        ('products', '0006_remove_product_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='order.orderproduct'),
        ),
    ]
