# Generated by Django 3.2.7 on 2021-09-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderProduct',
        ),
    ]
